services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-node1
    restart: always
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra_data:/var/lib/cassandra

  cassandra-init:
    image: cassandra:4.1
    container_name: cassandra-init
    depends_on:
      - cassandra
    volumes:
      - ./db/schema.cql:/schema.cql:ro
    entrypoint: >
      sh -c "
      echo 'Aguardando Cassandra iniciar...';
      until cqlsh cassandra-node1 9042 -f /schema.cql; do
        sleep 5;
      done;
      echo 'Schema criado com sucesso!';
      "

  redis:
    image: redis:latest
    container_name: meu-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  cassandra_data: