services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-node1
    restart: always
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - cassandra_data:/var/lib/cassandra
#  postgresdb:
#    image: postgres:15-alpine
#    container_name: postgres-container
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: url-shortener
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:latest
    container_name: meu-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
volumes:
  cassandra_data: